import time
print("1:Encrypt the data")
print("2:Decrypt the data")
a=int(input())
if a==1:
    mes=input("What is the messgae")
    mesa=mes.replace('a','*&#')
    mesab=mesa.replace('b','@#$')
    mun=mesab.replace('c','-_#')
    bn=mun.replace('d','/?#')
    gn=bn.replace('e','@^@')
    hb=gn.replace('f','!`#')
    ty=hb.replace('g','(@#')
    bg=ty.replace('h','/&-')
    kt=bg.replace('i','{||')
    rv=kt.replace('j','--_')
    cv=rv.replace('k','#$+')
    uy=cv.replace('l',';:_')
    rt=uy.replace('m','+==')
    pt=rt.replace('n','#&:')
    yg=pt.replace('o','#]{')
    un=yg.replace('p',';^!')
    df=un.replace('q','@?:')
    rh=df.replace('r','[+]')
    ph=rh.replace('s','<#@')
    rz=ph.replace('t','#>?')
    tu=rz.replace('u','|>{')
    ws=tu.replace('v','%)|')
    qs=ws.replace('w','#.,')
    lj=qs.replace('x',';^=')
    rf=lj.replace('y','//+')
    ys=rf.replace('z','##>')
    sy=ys.replace(' ','_')
    print("Encrypting the message")
    time.sleep(3)
    print("Message encrypted Here is the key")
    print(sy)
    a=open("Encoding.txt",'a')
    a.write(sy),'\n'
elif a==2:
    les=input("Enter the encrypted key")
    mesa = les.replace('*&#', 'a')
    mesab = mesa.replace('@#$', 'b')
    mun = mesab.replace('-_#', 'c')
    bn = mun.replace('/?#', 'd')
    gn = bn.replace('@^@', 'e')
    hb = gn.replace('!`#', 'f')
    ty = hb.replace('(@#', 'g')
    bg = ty.replace('/&-', 'h')
    kt = bg.replace('{||', 'i')
    rv = kt.replace('--_', 'j')
    cv = rv.replace('#$+', 'k')
    uy = cv.replace(';:_', 'l')
    rt = uy.replace('+==', 'm')
    pt = rt.replace('#&:', 'n')
    yg = pt.replace('#]{', 'o')
    un = yg.replace(';^!', 'p')
    df = un.replace('@?:', 'q')
    rh = df.replace('[+]', 'r')
    ph = rh.replace('<#@', 's')
    rz = ph.replace('#>?', 't')
    tu = rz.replace('|>{', 'u')
    ws = tu.replace('%)|', 'v')
    qs = ws.replace('#.,', 'w')
    lj = qs.replace(';^=', 'x')
    rf = lj.replace('//+', 'y')
    ys = rf.replace('##>', 'z')
    sy = ys.replace('_', ' ')
    print("Decrypting the key")
    print("Here is the decryption")
    print(sy)
